export const refs = {
  galleryLibraryEl: document.querySelector('.gallery-library'),
  searchMovieForm: document.querySelector('.search-movie-form'),
  sectionContainer: document.querySelector('.movies-section-container'),
  moviesList: document.querySelector('.js-movies-list'),
  weekBtn: document.querySelector('.week'),
  dayBtn: document.querySelector('.day'),
  libraryButtons: document.querySelector('.library-nav-list'),
  modalInfo: document.querySelector('.modal-movie-content'),
  modal: document.querySelector('.modal-movie-card'),
  loadingDots: document.querySelector('.loading-dot-stage'),
  infiniteScrollingAnchor: document.querySelector('.js-infinite-scrolling-anchor'),
  myLibraryIsActive: document.querySelector('.my-library'),
  myHomeIsActive: document.querySelector('.home'),
};
